apiVersion: v1
kind: Pod
metadata:
    name: webapp-color
    labels:
      name: webapp-color
spec:
    containers:
        -   name: redis
            image: redis
            envFrom:
              - configMapRef:
                  name: webapp-config-map

